package enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

import java.util.Arrays;
import java.util.List;

@Getter
@AllArgsConstructor
public enum ExerciseEnum {
    /**
     * Кардио упражнения
     */
    BAR_FACING_BURPEE("Берпи с перепрыгиванием через гриф", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BICYCLE("Езда на велосипеде", ExerciseTypeEnum.CARDIO, TrainingPartEnum.BASE_TRAINING, true, Arrays.asList(MeasurementUnitEnum.CAL, MeasurementUnitEnum.SEC, MeasurementUnitEnum.METTERS), Arrays.asList(5, 21), Arrays.asList(0, 0), Arrays.asList(5, 21), Arrays.asList(5, 21), Arrays.asList(5, 21), Arrays.asList(0, 0), Arrays.asList(5, 21), Arrays.asList(5, 21)),
    BOX_JUMP("Запрыгивание на коробку", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BOX_JUMP_OVER("Перепрыгивание через коробку", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BOX_STEP_UP("Зашагивание на коробку", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BURPEE("Берпи", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BURPEE_BOX_JUMP_OVER("Берпи с перепрыгванием через коробку", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BURPEE_MEDICINE_BALL("Берпи через медицинский мяч", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BURPEE_PLATE_JUMP("Берпи с запрыгиванием на коробку", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BURPEE_ROWING_MACHINE_OVER("Берпи с перепрыгиванием через греблю", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DOUBLE_UNDERS("Двойные прыжки на скакалке", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_BOX_STEP_UP("Зашагивание на коробку с гантелью", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    JUMPING_JACK("Прыгающий джек", ExerciseTypeEnum.CARDIO, TrainingPartEnum.WARM_UP, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    MEDICINE_BALL_CLEAN("Взятие на грудь медицинского мяча", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_MEDICINE_BALL_LUNGES("Выпады с медицинским мячом над головой", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    ROW("Гребля", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.CAL, MeasurementUnitEnum.SEC, MeasurementUnitEnum.METTERS), Arrays.asList(5, 16), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(50, 101), Arrays.asList(5, 16), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(50, 101)),
    RUN("Бег", ExerciseTypeEnum.CARDIO, TrainingPartEnum.BASE_TRAINING, true, Arrays.asList(MeasurementUnitEnum.CAL, MeasurementUnitEnum.SEC, MeasurementUnitEnum.METTERS), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    UNDERS("Одинарные прыжки на скакалке", ExerciseTypeEnum.CARDIO, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(40, 61), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(40, 61), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    /**
     * Гимнастические упражнения
     */
    AIR_SQUAD("Воздушные приседания", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.WARM_UP, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 21), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 21), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BAR_MUSCLE_UP("Выход силой на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BATTERFLY_PULL_UP("Подтягивания батерфляй", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    CHEST_TO_BAR_PULL_UP("Подтягивания до груди на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DEAD_BUG("Мертвый жук", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 21), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 21), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DIP("Отжимания на брусьях", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    STRICT_HANDSTAND_PUSH_UP("Строгин отжимания в стойке на руках", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HAND_STAND_WALK("Ходьба на руках", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.METTERS), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11)),
    KIPPING_BAR_MUSCLE_UP("Киппинговый выход силой на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KIPPING_BAR_PULL_UP("Киппинговые подтягивания на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KIPPING_HAND_STAND_PUSH_UP("Киппинговые отжимания в стойке на руках", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KIPPING_RING_MUSCLE_UP("Киппинговые выходы силой на кольцах", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.BASE_TRAINING, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KIPPING_TOES_TO_BAR("Киппинговые подносы носков к перекладине", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KNEE_TO_ELBOWS("Колени к локтям", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    L_HANG_HOLD("Удержание уголка в висе на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.SEC), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 11), Arrays.asList(0, 0)),
    PRESS_TO_HANDSTAND("Выход в стойку на руках", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.BASE_TRAINING, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    PUSH_UP("Отжимания", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    RING_DIP("Отжимания на кольцах", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    ROPE_CLIMB("Подъемы по канату", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 3), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 3), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    SIT_UP("Подъемы корпуса", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    STRICT_BAR_PULL_UP("Строгие подтягивания на турнике", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.BASE_TRAINING, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 6), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    STRICT_RING_MUSCLE_UP("Строгие выходы силой на кольцах", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.BASE_TRAINING, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(1, 2), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    STRICT_TOES_TO_BAR("Строгие подносы носков к перекладине", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    V_UP("Складишок", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.WARM_UP, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(10, 16), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    WALL_HAND_STAND("Стойка на руках у стены", ExerciseTypeEnum.GYMNASTIC, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.SEC), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(20, 31), Arrays.asList(0, 0)),
    /**
     * Тяжелоатлетические упражнения
     */
    BACK_SQUAT("Приседания со штангой на спине", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    BENCH_PRESS("Жим штанги", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    CLEAN("Взятие штанги на грудь", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    CLEAN_AND_JERK("Взятие и толчок", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    CLEAN_PULL_UP("Толчковая тяга", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    CLUSTER("Кластер", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DEADLIFT("Становая тяга", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_CLEAN("Взятие гантели на грудь", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_DEAD_LIFT("Становая тяга с гантелями", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_JERK("Толчок гантели", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_PRESS("Жим гантелей лёжа", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_SNATCH("Рывок гантели", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    DUMBBELL_THRUSTER("Трастеры с гантелями", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    FRONT_SQUAT("Фронтальные приседания", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    GOBLET_SQUAT("Приседания с гирей на груди", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HAMMER_SLAM("Удары кувалдой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HANG_POWER_CLEAN("Силовое взятие штанги на грудь с виса", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HANG_POWER_SNATCH("Силовой рывок в стойку с виса", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HANG_SNATCH("Рывок с виса в сед", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    HANG_SNATCH_HALF_SQUAT("Рывок с виса в полусед", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    JERK("Толчок", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    KETTLEBELL_SWING("Махи гирей", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_DUMBBELL_LUNGES("Выпады с гантелью над головой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_DUMBBELL_SQUAT("Приседания с гантелью над головой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_LUNGES("Выпады со штангой над головой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_PLATE_LUNGES("Выпады с блином над головой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    OVER_HEAD_SQUAT("Приседания со штангой над головой", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    POWER_CLEAN("Силовое взятие штанги на грудь", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    POWER_SNATCH("Силовой рывок в стойку", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    PUSH_JERK("Толчковый швунг", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    PUSH_PRESS("Жимовой жвунг", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    SHOULDER_PRESS("Жим штанги стоя", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    SNATCH("Рывок", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    SNATCH_PULL("Рывковая тяга", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.BASE_TRAINING, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    SUMO_DEAD_LIFT_HIGH_PULL("Становая тяга сумо до подбородка", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    THRUSTER("Трастер", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, true, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    WALKING_LUNGES("Шагающие выпады", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0)),
    WALL_BALL("Броски медицинского мяча в стену", ExerciseTypeEnum.WEIGHTLIFTING, TrainingPartEnum.UNIVERSAL, false, Arrays.asList(MeasurementUnitEnum.REP), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(0, 0), Arrays.asList(5, 11), Arrays.asList(0, 0), Arrays.asList(0, 0));

    private String exerciseName;
    private ExerciseTypeEnum exerciseType;
    private TrainingPartEnum trainingPart;
    private boolean isLong;
    private List<MeasurementUnitEnum> measurementUnits;
    private List<Integer> minMaxCalValuesForWarmUp;
    private List<Integer> minMaxRepValuesForWarmUp;
    private List<Integer> minMaxSecValuesForWarmUp;
    private List<Integer> minMaxMetterValuesForWarmUp;
    private List<Integer> minMaxCalValuesForBaseTraining;
    private List<Integer> minMaxRepValuesForBaseTraining;
    private List<Integer> minMaxSecValuesForBaseTraining;
    private List<Integer> minMaxMetterValuesForBaseTraining;

}
